// Created by Vojtech Bruza

using UnityEngine;

namespace UVRN.Player
{
    public static class PlayerProfileManager
    {
        private static string[] adjectives =
                {
                "Affectionate",
                "Agreeable",
                "Amiable",
                "Bright",
                "Charming",
                "Creative",
                "Determined",
                "Energetic",
                "Friendly",
                "Funny",
                "Generous",
                "Imaginative",
                "Polite",
                "Likable",
                "Gregarious",
                "Diplomatic",
                "Sincere",
                "Helpful",
                "Giving",
                "Kind",
                "Hardworking",
                "Diligent",
                "Patient",
                "Dynamic",
                "Loyal",
                "Brave",
                "Self-confident",
                "Sensible",
                "Sincere",
                "Thoughtful",
                "Warmhearted",
                "Willing",
                "Proficient",
                "Romantic",
                "Powerful",
                "Persistent",
                "Passionate",
                "Loving",
                "Faithful",
                "Nice",
                "Optimistic",
                "Plucky",
                "Philosophical",
                "Humorous",
                "Frank",
                "Fearless",
                "Considerate",
                "Courageous",
                "Marvelous",
                "Capable",
                "Accomplished",
                "Knowledgeable",
                "Adept",
                "Expert",
                "Engaging",
                "Amazing",
                "Awesome",
                "Blithesome",
                "Excellent",
                "Fabulous",
                "Fantastic",
                "Favorable",
                "Fortuitous",
                "Gorgeous",
                "Incredible",
                "Unique",
                "Mirthful",
                "Outstanding",
                "Perfect",
                "Propitious",
                "Remarkable",
                "Rousing",
                "Spectacular",
                "Splendid",
                "Stellar",
                "Stupendous",
                "Super",
                "Upbeat",
                "Stunning",
                "Wondrous",
                "Ample",
                "Bountiful",
                "Glistening",
                "Dazzling",
                "Twinkling",
                "Lustrous",
                "Vivid",
                "Vibrant",
                "Vivacious",
                "Glowing",
                "Gleaming",
                "Sparkling",
                "Shimmering",
                "Glimmering",
                "Glittering",
                "Brilliant",
                "Elegant",
                "Sleek",
                "Alluring",
                "Enchanting",
                "Ravishing",
                "Magnificent",
                "Captivating",
                "Lovely",
                "Glowing",
                "Flexible",
                "Independent",
                "Insightful",
                "Open-minded",
                "Productive",
                "Adventurous",
                "Articulate",
                "Charismatic",
                "Competitive",
                "Confident",
                "Devoted",
                "Educated",
                "Inquisitive",
                "Organized",
                "Relaxed",
                "Responsible",
                "Technological",
                "Resourceful",
                "Ambitious",
                "Approachable",
                "Qualified",
                "Focused",
                "Honest",
                "Efficient",
                "Personable",
            };
        private static string[] animals =
                {
                "Alligator",
                "Armadillo",
                "Bear",
                "Beaver",
                "Butterfly",
                "Camel",
                "Chicken",
                "Chipmunk",
                "Cougar",
                "Coyote",
                "Crocodile",
                "Crab",
                "Crayfish",
                "Crow",
                "Dinosaur",
                "Dolphin",
                "Donkey",
                "Dragonfly",
                "Deer",
                "Duck",
                "Eagle",
                "Earthworm",
                "Elephant",
                "Fish",
                "Frog",
                "Gerbil",
                "Giraffe",
                "Goat",
                "Goose",
                "Gopher",
                "Hamster",
                "Hawk",
                "Hedgehog",
                "Hippopotamus",
                "Horse",
                "Jellyfish",
                "Kangaroo",
                "Kitten",
                "Koala",
                "Leopard",
                "Lion",
                "Lizard",
                "Monkey",
                "Moose",
                "Mosquito",
                "Mouse",
                "Octopus",
                "Oyster",
                "Parrot",
                "Panda",
                "Panther",
                "Pelican",
                "Penguin",
                "Piglet",
                "Pigeon",
                "Rabbit",
                "Reindeer",
                "Rhinoceros",
                "Shark",
                "Sheep",
                "Skunk",
                "Snail",
                "Snake",
                "Spider",
                "Squirrel",
                "Tiger",
                "Tortoise",
                "Turkey",
                "Turtle",
                "Whale",
                "Wolf",
                "Woodpecker",
                "Worm",
                "Zebra",
            };

        // TODO load local profile from persistent memory
        public static readonly PlayerProfile LOCAL_PROFILE = new()
        {
            username = GetRandomName(),
            password = "",
            role = "default",
            color = Color.HSVToRGB(Random.Range(0f, 1f), .75f, .75f),
            visibleAvatar = true,
        };

        public static string GetRandomName()
        {
            return $"{GetRandomAdjective()} {GetRandomAnimal()}";
        }

        private static string GetRandomAdjective()
        {
            return adjectives[Random.Range(0, adjectives.Length)];
        }
        private static string GetRandomAnimal()
        {
            return animals[Random.Range(0, animals.Length)];
        }
    }
}
